Update install for armhf install
YunoHost-Apps/mautrix_signal_ynh pull request #87
Opened 2023-09-05 20:30 UTC by rosbeef

## Problem

- install/upgrade/... not working on armhf

## Solution

-  work on armhf
## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

2023-09-06 14:23 UTC, MayeulC requested changes
Thank you for the report. I am not sure this is the cleanest solution, however. And there seems to be unrelated changes too? Could you comment on why there are necessary?

2023-09-06 23:39 UTC, rosbeef commented
hi @MayeulC i did changes and i tested installation and it works for me

2023-09-12 16:16 UTC, gautz commented on scripts/install
> +    sudo -u "$app" bash -c 'curl -sSf -L https://static.rust-lang.org/rustup.sh | sh -s -- -y --default-toolchain=stable --profile=minimal'
ping @tituspijean @ericgaspar do you think this makes sense ? Would packaging v2 solve this armhf install issue in a cleaner way ?

2023-09-23 20:19 UTC, nathanael-h commented
!test-me

2023-09-23 20:21 UTC, nathanael-h commented
!testme

2024-01-26 11:14 UTC, merged